name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      TOML_VERSION: v3.4.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clone upstream repository
        run: git clone --depth 1 -b ${{ env.TOML_VERSION }} https://github.com/marzer/tomlplusplus
      - name: Verify file
        run: diff toml.hpp tomlplusplus/toml.hpp